package com.mrbysco.miab.registry;

import com.mrbysco.miab.Reference;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class MemeSounds {
	public static final DeferredRegister<SoundEvent> SOUND_EVENTS = DeferredRegister.create(BuiltInRegistries.SOUND_EVENT, Reference.MOD_ID);

	public static final DeferredHolder<SoundEvent, SoundEvent> cena_spawn = SOUND_EVENTS.register("cena.spawn", () -> createSound("cena.spawn"));
	public static final DeferredHolder<SoundEvent, SoundEvent> cena_sound = SOUND_EVENTS.register("cena.sound", () -> createSound("cena.sound"));
	public static final DeferredHolder<SoundEvent, SoundEvent> trump_spawn = SOUND_EVENTS.register("trump.spawn", () -> createSound("trump.spawn"));
	public static final DeferredHolder<SoundEvent, SoundEvent> trump_sound = SOUND_EVENTS.register("trump.sound", () -> createSound("trump.sound"));
	public static final DeferredHolder<SoundEvent, SoundEvent> trump_hit = SOUND_EVENTS.register("trump.hit", () -> createSound("trump.hit"));
	public static final DeferredHolder<SoundEvent, SoundEvent> trump_death = SOUND_EVENTS.register("trump.death", () -> createSound("trump.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> inception = SOUND_EVENTS.register("inception", () -> createSound("inception"));
	public static final DeferredHolder<SoundEvent, SoundEvent> khil_spawn = SOUND_EVENTS.register("khil.spawn", () -> createSound("khil.spawn"));
	public static final DeferredHolder<SoundEvent, SoundEvent> khil_sound = SOUND_EVENTS.register("khil.sound", () -> createSound("khil.sound"));
	public static final DeferredHolder<SoundEvent, SoundEvent> khil_death = SOUND_EVENTS.register("khil.death", () -> createSound("khil.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_spawn = SOUND_EVENTS.register("ppap.spawn", () -> createSound("ppap.spawn"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_sound = SOUND_EVENTS.register("ppap.sound", () -> createSound("ppap.sound"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_death = SOUND_EVENTS.register("ppap.death", () -> createSound("ppap.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_havepen = SOUND_EVENTS.register("ppap.havepen", () -> createSound("ppap.havepen"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_havepineapple = SOUND_EVENTS.register("ppap.havepineapple", () -> createSound("ppap.havepineapple"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_haveapple = SOUND_EVENTS.register("ppap.haveapple", () -> createSound("ppap.haveapple"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_applepen = SOUND_EVENTS.register("ppap.applepen", () -> createSound("ppap.applepen"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_pineapplepen = SOUND_EVENTS.register("ppap.pineapplepen", () -> createSound("ppap.pineapplepen"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_ahapplepen = SOUND_EVENTS.register("ppap.ahapplepen", () -> createSound("ppap.ahapplepen"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_ahpineapplepen = SOUND_EVENTS.register("ppap.ahpineapplepen", () -> createSound("ppap.ahpineapplepen"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ppap_ppap = SOUND_EVENTS.register("ppap.ppap", () -> createSound("ppap.ppap"));
	public static final DeferredHolder<SoundEvent, SoundEvent> boi_summon = SOUND_EVENTS.register("boi.spawn", () -> createSound("boi.spawn"));
	public static final DeferredHolder<SoundEvent, SoundEvent> boi_passive = SOUND_EVENTS.register("boi.passive", () -> createSound("boi.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> boi_death = SOUND_EVENTS.register("boi.death", () -> createSound("boi.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shrek_summon = SOUND_EVENTS.register("shrek.spawn", () -> createSound("shrek.spawn"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shrek_passive = SOUND_EVENTS.register("shrek.passive", () -> createSound("shrek.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shrek_hit = SOUND_EVENTS.register("shrek.hit", () -> createSound("shrek.hit"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shrek_death = SOUND_EVENTS.register("shrek.death", () -> createSound("shrek.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shrek_onion = SOUND_EVENTS.register("shrek.onion", () -> createSound("shrek.onion"));
	public static final DeferredHolder<SoundEvent, SoundEvent> robbie_summon = SOUND_EVENTS.register("robbie.summon", () -> createSound("robbie.summon"));
	public static final DeferredHolder<SoundEvent, SoundEvent> robbie_passive = SOUND_EVENTS.register("robbie.passive", () -> createSound("robbie.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> robbie_sax = SOUND_EVENTS.register("robbie.sax", () -> createSound("robbie.sax"));
	public static final DeferredHolder<SoundEvent, SoundEvent> robbie_sax2 = SOUND_EVENTS.register("robbie.sax2", () -> createSound("robbie.sax2"));
	public static final DeferredHolder<SoundEvent, SoundEvent> robbie_hit = SOUND_EVENTS.register("robbie.hit", () -> createSound("robbie.hit"));
	public static final DeferredHolder<SoundEvent, SoundEvent> robbie_death = SOUND_EVENTS.register("robbie.death", () -> createSound("robbie.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dad_summon = SOUND_EVENTS.register("dad.summon", () -> createSound("dad.summon"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dad_passive = SOUND_EVENTS.register("dad.passive", () -> createSound("dad.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dad_hit = SOUND_EVENTS.register("dad.hit", () -> createSound("dad.hit"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dad_death = SOUND_EVENTS.register("dad.death", () -> createSound("dad.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> leather_belt = SOUND_EVENTS.register("leather.belt", () -> createSound("leather.belt"));
	public static final DeferredHolder<SoundEvent, SoundEvent> cry = SOUND_EVENTS.register("fa.cry", () -> createSound("fa.cry"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dankey_summon = SOUND_EVENTS.register("dankey.summon", () -> createSound("dankey.summon"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dankey_passive = SOUND_EVENTS.register("dankey.passive", () -> createSound("dankey.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dankey_hit = SOUND_EVENTS.register("dankey.hit", () -> createSound("dankey.hit"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dankey_death = SOUND_EVENTS.register("dankey.death", () -> createSound("dankey.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> sanic_slow = SOUND_EVENTS.register("sanic.slow", () -> createSound("sanic.slow"));
	public static final DeferredHolder<SoundEvent, SoundEvent> nigel_blagh = SOUND_EVENTS.register("nigel.blagh", () -> createSound("nigel.blagh"));
	public static final DeferredHolder<SoundEvent, SoundEvent> skywalker_sand = SOUND_EVENTS.register("skywalker.sand", () -> createSound("skywalker.sand"));
	public static final DeferredHolder<SoundEvent, SoundEvent> pills = SOUND_EVENTS.register("pills.here", () -> createSound("pills.here"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shaq_summon = SOUND_EVENTS.register("shaq.summon", () -> createSound("shaq.summon"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shaq_hit = SOUND_EVENTS.register("shaq.hit", () -> createSound("shaq.hit"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shaq_passive = SOUND_EVENTS.register("shaq.passive", () -> createSound("shaq.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> shaq_death = SOUND_EVENTS.register("shaq.death", () -> createSound("shaq.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> big_boi = SOUND_EVENTS.register("meme.bigboi", () -> createSound("meme.bigboi"));
	public static final DeferredHolder<SoundEvent, SoundEvent> hotdog_tune = SOUND_EVENTS.register("hotdog.tune", () -> createSound("hotdog.tune"));
	public static final DeferredHolder<SoundEvent, SoundEvent> hotdog_full = SOUND_EVENTS.register("hotdog.full", () -> createSound("hotdog.full"));
	public static final DeferredHolder<SoundEvent, SoundEvent> heman_spawn = SOUND_EVENTS.register("heman.summon", () -> createSound("heman.summon"));
	public static final DeferredHolder<SoundEvent, SoundEvent> heman_hit = SOUND_EVENTS.register("heman.hit", () -> createSound("heman.hit"));
	public static final DeferredHolder<SoundEvent, SoundEvent> heman_passive = SOUND_EVENTS.register("heman.passive", () -> createSound("heman.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> heman_death = SOUND_EVENTS.register("heman.death", () -> createSound("heman.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> clippy_mineshaft = SOUND_EVENTS.register("clippy.mineshaft", () -> createSound("clippy.mineshaft"));
	public static final DeferredHolder<SoundEvent, SoundEvent> clippy_cave = SOUND_EVENTS.register("clippy.cave", () -> createSound("clippy.cave"));
	public static final DeferredHolder<SoundEvent, SoundEvent> clippy_night = SOUND_EVENTS.register("clippy.night", () -> createSound("clippy.night"));
	public static final DeferredHolder<SoundEvent, SoundEvent> clippy_health = SOUND_EVENTS.register("clippy.health", () -> createSound("clippy.health"));
	public static final DeferredHolder<SoundEvent, SoundEvent> clippy_death = SOUND_EVENTS.register("clippy.death", () -> createSound("clippy.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> clippy_hurt = SOUND_EVENTS.register("clippy.hurt", () -> createSound("clippy.hurt"));
	public static final DeferredHolder<SoundEvent, SoundEvent> clippy_passive = SOUND_EVENTS.register("clippy.passive", () -> createSound("clippy.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> clippy_forest = SOUND_EVENTS.register("clippy.forest", () -> createSound("clippy.forest"));
	public static final DeferredHolder<SoundEvent, SoundEvent> boing = SOUND_EVENTS.register("clippy.jump", () -> createSound("clippy.jump"));
	public static final DeferredHolder<SoundEvent, SoundEvent> knuckles_passive = SOUND_EVENTS.register("knuckles.passive", () -> createSound("knuckles.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> knuckles_hurt = SOUND_EVENTS.register("knuckles.hurt", () -> createSound("knuckles.hurt"));
	public static final DeferredHolder<SoundEvent, SoundEvent> knuckles_death = SOUND_EVENTS.register("knuckles.death", () -> createSound("knuckles.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> rofl_spawn = SOUND_EVENTS.register("rofl.summon", () -> createSound("rofl.summon"));
	public static final DeferredHolder<SoundEvent, SoundEvent> rofl_passive = SOUND_EVENTS.register("rofl.passive", () -> createSound("rofl.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> rofl_hurt = SOUND_EVENTS.register("rofl.hurt", () -> createSound("rofl.hurt"));
	public static final DeferredHolder<SoundEvent, SoundEvent> rofl_death = SOUND_EVENTS.register("rofl.death", () -> createSound("rofl.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> gnome_spawn = SOUND_EVENTS.register("gnome.summon", () -> createSound("gnome.summon"));
	public static final DeferredHolder<SoundEvent, SoundEvent> gnome_passive = SOUND_EVENTS.register("gnome.passive", () -> createSound("gnome.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> gnome_hurt = SOUND_EVENTS.register("gnome.hurt", () -> createSound("gnome.hurt"));
	public static final DeferredHolder<SoundEvent, SoundEvent> gnome_death = SOUND_EVENTS.register("gnome.death", () -> createSound("gnome.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> phil_lottadamage = SOUND_EVENTS.register("phil.lottadamage", () -> createSound("phil.lottadamage"));
	public static final DeferredHolder<SoundEvent, SoundEvent> phil_passive = SOUND_EVENTS.register("phil.passive", () -> createSound("phil.passive"));
	public static final DeferredHolder<SoundEvent, SoundEvent> phil_hurt = SOUND_EVENTS.register("phil.hurt", () -> createSound("phil.hurt"));
	public static final DeferredHolder<SoundEvent, SoundEvent> phil_death = SOUND_EVENTS.register("phil.death", () -> createSound("phil.death"));
	public static final DeferredHolder<SoundEvent, SoundEvent> sans_sound = SOUND_EVENTS.register("sans.sound", () -> createSound("sans.sound"));
	public static final DeferredHolder<SoundEvent, SoundEvent> tom_sound = SOUND_EVENTS.register("tom.sound", () -> createSound("tom.sound"));

	//Start of records
	public static final DeferredHolder<SoundEvent, SoundEvent> meme_music1 = SOUND_EVENTS.register("meme.record1", () -> createSound("meme.record1"));
	public static final DeferredHolder<SoundEvent, SoundEvent> meme_music2 = SOUND_EVENTS.register("meme.record2", () -> createSound("meme.record2"));

	//Start of main MEME sounds
	public static final DeferredHolder<SoundEvent, SoundEvent> ninethousand = SOUND_EVENTS.register("9000", () -> createSound("9000"));
	public static final DeferredHolder<SoundEvent, SoundEvent> barrelroll = SOUND_EVENTS.register("barrelroll", () -> createSound("barrelroll"));
	public static final DeferredHolder<SoundEvent, SoundEvent> biwinning = SOUND_EVENTS.register("bi.winning", () -> createSound("bi.winning"));
	public static final DeferredHolder<SoundEvent, SoundEvent> boomheadshot = SOUND_EVENTS.register("boomheadshot", () -> createSound("boomheadshot"));
	public static final DeferredHolder<SoundEvent, SoundEvent> callinthenext = SOUND_EVENTS.register("callinthenext", () -> createSound("callinthenext"));
	public static final DeferredHolder<SoundEvent, SoundEvent> cantbelieve = SOUND_EVENTS.register("cantbelieve", () -> createSound("cantbelieve"));
	public static final DeferredHolder<SoundEvent, SoundEvent> charliebitme = SOUND_EVENTS.register("charliebitme", () -> createSound("charliebitme"));
	public static final DeferredHolder<SoundEvent, SoundEvent> chocolate = SOUND_EVENTS.register("chocolate", () -> createSound("chocolate"));
	public static final DeferredHolder<SoundEvent, SoundEvent> congratz = SOUND_EVENTS.register("congratz", () -> createSound("congratz"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dedidadedwam = SOUND_EVENTS.register("dedidadedwam", () -> createSound("dedidadedwam"));
	public static final DeferredHolder<SoundEvent, SoundEvent> deeznuts = SOUND_EVENTS.register("deeznuts", () -> createSound("deeznuts"));
	public static final DeferredHolder<SoundEvent, SoundEvent> doit = SOUND_EVENTS.register("doit", () -> createSound("doit"));
	public static final DeferredHolder<SoundEvent, SoundEvent> dontletyourdreamsbedreams = SOUND_EVENTS.register("dontletyourdreamsbedreams", () -> createSound("dontletyourdreamsbedreams"));
	public static final DeferredHolder<SoundEvent, SoundEvent> doot = SOUND_EVENTS.register("dootdoot", () -> createSound("dootdoot"));
	public static final DeferredHolder<SoundEvent, SoundEvent> gaben = SOUND_EVENTS.register("gaben", () -> createSound("gaben"));
	public static final DeferredHolder<SoundEvent, SoundEvent> getitoxyclean = SOUND_EVENTS.register("getitoxyclean", () -> createSound("getitoxyclean"));
	public static final DeferredHolder<SoundEvent, SoundEvent> getnoscoped = SOUND_EVENTS.register("getnoscoped", () -> createSound("getnoscoped"));
	public static final DeferredHolder<SoundEvent, SoundEvent> gotchab = SOUND_EVENTS.register("gotchab", () -> createSound("gotchab"));
	public static final DeferredHolder<SoundEvent, SoundEvent> hagay = SOUND_EVENTS.register("hahappy", () -> createSound("hahappy"));
	public static final DeferredHolder<SoundEvent, SoundEvent> k = SOUND_EVENTS.register("k", () -> createSound("k"));
	public static final DeferredHolder<SoundEvent, SoundEvent> leroyjenkins = SOUND_EVENTS.register("leroyjenkins", () -> createSound("leroyjenkins"));
	public static final DeferredHolder<SoundEvent, SoundEvent> momscar = SOUND_EVENTS.register("momscar", () -> createSound("momscar"));
	public static final DeferredHolder<SoundEvent, SoundEvent> morningscrub = SOUND_EVENTS.register("morningscrub", () -> createSound("morningscrub"));
	public static final DeferredHolder<SoundEvent, SoundEvent> nice = SOUND_EVENTS.register("nice", () -> createSound("nice"));
	public static final DeferredHolder<SoundEvent, SoundEvent> nicememe = SOUND_EVENTS.register("nicememe", () -> createSound("nicememe"));
	public static final DeferredHolder<SoundEvent, SoundEvent> noot = SOUND_EVENTS.register("noot", () -> createSound("noot"));
	public static final DeferredHolder<SoundEvent, SoundEvent> nothisispatrick = SOUND_EVENTS.register("nothisispatrick", () -> createSound("nothisispatrick"));
	public static final DeferredHolder<SoundEvent, SoundEvent> nothisispatrick2 = SOUND_EVENTS.register("nothisispatrick2", () -> createSound("nothisispatrick2"));
	public static final DeferredHolder<SoundEvent, SoundEvent> noticeme = SOUND_EVENTS.register("noticeme", () -> createSound("noticeme"));
	public static final DeferredHolder<SoundEvent, SoundEvent> ohlongjohnson = SOUND_EVENTS.register("ohlongjohnson", () -> createSound("ohlongjohnson"));
	public static final DeferredHolder<SoundEvent, SoundEvent> oldspicepower = SOUND_EVENTS.register("oldspicepower", () -> createSound("oldspicepower"));
	public static final DeferredHolder<SoundEvent, SoundEvent> oxyclean = SOUND_EVENTS.register("oxyclean", () -> createSound("oxyclean"));
	public static final DeferredHolder<SoundEvent, SoundEvent> rightinthe = SOUND_EVENTS.register("rightinthe", () -> createSound("rightinthe"));
	public static final DeferredHolder<SoundEvent, SoundEvent> sandwich = SOUND_EVENTS.register("sandwich", () -> createSound("sandwich"));
	public static final DeferredHolder<SoundEvent, SoundEvent> smokeweed = SOUND_EVENTS.register("smokew", () -> createSound("smokew"));
	public static final DeferredHolder<SoundEvent, SoundEvent> snooppengas = SOUND_EVENTS.register("snooppen", () -> createSound("snooppen"));
	public static final DeferredHolder<SoundEvent, SoundEvent> somebodystopme = SOUND_EVENTS.register("somebodystopme", () -> createSound("somebodystopme"));
	public static final DeferredHolder<SoundEvent, SoundEvent> sparta = SOUND_EVENTS.register("sparta", () -> createSound("sparta"));
	public static final DeferredHolder<SoundEvent, SoundEvent> spongebobsound = SOUND_EVENTS.register("spongebobsound", () -> createSound("spongebobsound"));
	public static final DeferredHolder<SoundEvent, SoundEvent> triple = SOUND_EVENTS.register("triple", () -> createSound("triple"));
	public static final DeferredHolder<SoundEvent, SoundEvent> trololo = SOUND_EVENTS.register("trololo", () -> createSound("trololo"));
	public static final DeferredHolder<SoundEvent, SoundEvent> victoryscreech = SOUND_EVENTS.register("victoryscreech", () -> createSound("victoryscreech"));
	public static final DeferredHolder<SoundEvent, SoundEvent> wasted = SOUND_EVENTS.register("wasted", () -> createSound("wasted"));
	public static final DeferredHolder<SoundEvent, SoundEvent> whiten = SOUND_EVENTS.register("whiten", () -> createSound("whiten"));
	public static final DeferredHolder<SoundEvent, SoundEvent> wololo = SOUND_EVENTS.register("wololo", () -> createSound("wololo"));
	public static final DeferredHolder<SoundEvent, SoundEvent> wombocombo = SOUND_EVENTS.register("wombocombo", () -> createSound("wombocombo"));
	public static final DeferredHolder<SoundEvent, SoundEvent> wow = SOUND_EVENTS.register("wow", () -> createSound("wow"));
	public static final DeferredHolder<SoundEvent, SoundEvent> wrong = SOUND_EVENTS.register("wrong", () -> createSound("wrong"));
	public static final DeferredHolder<SoundEvent, SoundEvent> wrongnumber = SOUND_EVENTS.register("wrongnumber", () -> createSound("wrongnumber"));
	public static final DeferredHolder<SoundEvent, SoundEvent> thuglife = SOUND_EVENTS.register("thug.life", () -> createSound("thug.life"));
	public static final DeferredHolder<SoundEvent, SoundEvent> pufferfish = SOUND_EVENTS.register("pufferfish.augh", () -> createSound("pufferfish.augh"));

	private static SoundEvent createSound(String name) {
		ResourceLocation resourceLocation = Reference.modLoc(name);
		SoundEvent sound = SoundEvent.createVariableRangeEvent(resourceLocation);
		return sound;
	}
}
