# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Base info
mc_version=1.21.1
neo_version=21.1.141
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.miab
mod_id=miab
mod_archive_name=MemeInABottle

#Publishing
mod_name=Meme In A Bottle
curseforge_id=240830
modrinth_id=B02QopDj

# Version
version=6.0.0

# Dependencies
jei_minecraft=1.21.1
jei_version=19.21.0.247
crafttweaker_version=21.0.24