modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/mrbysco/memeinabottle/issues"
license="MIT"

[[mods]]
modId="memeinabottle"
version="${file.jarVersion}"
displayName="Meme in a bottle"
displayURL="https://minecraft.curseforge.com/projects/meme-in-a-bottle"
authors="Mrbysco"
description='''Adding (stale) Memes to Minecraft since 2016'''

[[dependencies.memeinabottle]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"