modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/mrbysco/memeinabottle/issues"

[[mods]]
modId="memeinabottle"
version="${file.jarVersion}"
displayName="Meme in a bottle"
displayURL="https://minecraft.curseforge.com/projects/meme-in-a-bottle"
authors="Mrbysco"
description='''Adding Memes to Minecraft since 2016'''