modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/mrbysco/memeinabottle/issues"

[[mods]]
modId="memeinabottle"
version="${file.jarVersion}"
displayName="Meme in a bottle"
displayURL="https://minecraft.curseforge.com/projects/meme-in-a-bottle"
authors="Mrbysco"
description='''Adding Memes to Minecraft since 2016'''

[[dependencies.memeinabottle]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.memeinabottle]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"