modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/mrbysco/memeinabottle/issues"
license="MIT"

[[mods]]
modId="memeinabottle"
version="${file.jarVersion}"
displayName="Meme in a bottle"
displayURL="https://www.curseforge.com/minecraft/mc-mods/meme-in-a-bottle"
authors="Mrbysco"
description='''Adding (stale) Memes to Minecraft since 2016'''

[[dependencies.memeinabottle]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.memeinabottle]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"