package com.mrbysco.miab.init;

import com.google.common.collect.Lists;
import com.mrbysco.miab.Reference;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.util.List;

@Mod.EventBusSubscriber(modid = Reference.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class MemeSounds {
	private static List<SoundEvent> sounds = Lists.newArrayList();

	public static SoundEvent cena_spawn;
	public static SoundEvent cena_sound;
	public static SoundEvent trump_spawn;
	public static SoundEvent trump_sound;
	public static SoundEvent trump_hit;
	public static SoundEvent trump_death;
	public static SoundEvent inception;
	public static SoundEvent khil_spawn;
	public static SoundEvent khil_sound;
	public static SoundEvent khil_death;
	public static SoundEvent ppap_spawn;
	public static SoundEvent ppap_sound;
	public static SoundEvent ppap_death;
	public static SoundEvent ppap_havepen;
	public static SoundEvent ppap_havepineapple;
	public static SoundEvent ppap_haveapple;
	public static SoundEvent ppap_applepen;
	public static SoundEvent ppap_pineapplepen;
	public static SoundEvent ppap_ahapplepen;
	public static SoundEvent ppap_ahpineapplepen;
	public static SoundEvent ppap_ppap;
	public static SoundEvent keyboard_mechanical;
	public static SoundEvent boi_summon;
	public static SoundEvent boi_passive;
	public static SoundEvent boi_death;
	public static SoundEvent shrek_summon;
	public static SoundEvent shrek_passive;
	public static SoundEvent shrek_hit;
	public static SoundEvent shrek_death;
	public static SoundEvent shrek_onion;
	public static SoundEvent robbie_summon;
	public static SoundEvent robbie_passive;
	public static SoundEvent robbie_sax;
	public static SoundEvent robbie_sax2;
	public static SoundEvent robbie_hit;
	public static SoundEvent robbie_death;
	public static SoundEvent dad_summon;
	public static SoundEvent dad_passive;
	public static SoundEvent dad_hit;
	public static SoundEvent dad_death;
	public static SoundEvent leather_belt;
	public static SoundEvent cry;
	public static SoundEvent dankey_summon;
	public static SoundEvent dankey_passive;
	public static SoundEvent dankey_hit;
	public static SoundEvent dankey_death;
	public static SoundEvent sanic_slow;
	public static SoundEvent nigel_blagh;
	public static SoundEvent meme_music;
	public static SoundEvent meme_music2;
	public static SoundEvent meme_music3;
	public static SoundEvent meme_music4;
	public static SoundEvent skywalker_sand;
	public static SoundEvent pills;
	public static SoundEvent shaq_summon;
	public static SoundEvent shaq_hit;
	public static SoundEvent shaq_passive;
	public static SoundEvent shaq_death;
	public static SoundEvent big_boi;
	public static SoundEvent hotdog_tune;
	public static SoundEvent hotdog_full;
	public static SoundEvent heman_spawn;
	public static SoundEvent heman_hit;
	public static SoundEvent heman_passive;
	public static SoundEvent heman_death;
	public static SoundEvent knuckles_passive;
	public static SoundEvent knuckles_hurt;
	public static SoundEvent knuckles_death;
	public static SoundEvent rofl_spawn;
	public static SoundEvent rofl_passive;
	public static SoundEvent rofl_hurt;
	public static SoundEvent rofl_death;
	public static SoundEvent gnome_spawn;
	public static SoundEvent gnome_passive;
	public static SoundEvent gnome_hurt;
	public static SoundEvent gnome_death;
	public static SoundEvent phil_lottadamage;
	public static SoundEvent phil_passive;
	public static SoundEvent phil_hurt;
	public static SoundEvent phil_death;
	public static SoundEvent clippy_mineshaft;
	public static SoundEvent clippy_cave;
	public static SoundEvent clippy_night;
	public static SoundEvent clippy_health;
	public static SoundEvent clippy_death;
	public static SoundEvent clippy_hurt;
	public static SoundEvent clippy_passive;
	public static SoundEvent clippy_forest;
	public static SoundEvent sans_sound;
	public static SoundEvent tom_sound;

	//start of main MEME sounds
	public static SoundEvent ninethousand;
	public static SoundEvent barrelroll;
	public static SoundEvent biwinning;
	public static SoundEvent boomheadshot;
	public static SoundEvent callinthenext;
	public static SoundEvent cantbelieve;
	public static SoundEvent charliebitme;
	public static SoundEvent chocolate;
	public static SoundEvent congratz;
	public static SoundEvent dedidadedwam;
	public static SoundEvent deeznuts;
	public static SoundEvent doit;
	public static SoundEvent dontletyourdreamsbedreams;
	public static SoundEvent doot;
	public static SoundEvent gaben;
	public static SoundEvent getitoxyclean;
	public static SoundEvent getnoscoped;
	public static SoundEvent gotchab;
	public static SoundEvent hagay;
	public static SoundEvent k;
	public static SoundEvent leroyjenkins;
	public static SoundEvent momscar;
	public static SoundEvent morningscrub;
	public static SoundEvent nice;
	public static SoundEvent nicememe;
	public static SoundEvent noot;
	public static SoundEvent nothisispatrick;
	public static SoundEvent nothisispatrick2;
	public static SoundEvent noticeme;
	public static SoundEvent ohlongjohnson;
	public static SoundEvent oldspicepower;
	public static SoundEvent oxyclean;
	public static SoundEvent rightinthe;
	public static SoundEvent sandwich;
	public static SoundEvent smokeweed;
	public static SoundEvent snooppengas;
	public static SoundEvent somebodystopme;
	public static SoundEvent sparta;
	public static SoundEvent spongebobsound;
	public static SoundEvent triple;
	public static SoundEvent trololo;
	public static SoundEvent victoryscreech;
	public static SoundEvent wasted;
	public static SoundEvent whiten;
	public static SoundEvent wololo;
	public static SoundEvent wombocombo;
	public static SoundEvent wow;
	public static SoundEvent wrong;
	public static SoundEvent wrongnumber;
	public static SoundEvent thuglife;
	public static SoundEvent boing;
	
	public static void registerSounds() 
	{
		cena_spawn = createSound("cena.spawn");
		cena_sound = createSound("cena.sound");
		trump_spawn = createSound("trump.spawn");
		trump_sound = createSound("trump.sound");
		trump_hit = createSound("trump.hit");
		trump_death = createSound("trump.death");
		inception = createSound("inception");
		khil_spawn = createSound("khil.spawn");
		khil_sound = createSound("khil.sound");
		khil_death = createSound("khil.death");
		ppap_spawn = createSound("ppap.spawn");
		ppap_sound = createSound("ppap.sound");
		ppap_death = createSound("ppap.death");
		ppap_havepen = createSound("ppap.havepen");
		ppap_havepineapple = createSound("ppap.havepineapple");
		ppap_haveapple = createSound("ppap.haveapple");
		ppap_applepen = createSound("ppap.applepen");
		ppap_pineapplepen = createSound("ppap.pineapplepen");
		ppap_ahapplepen = createSound("ppap.ahapplepen");
		ppap_ahpineapplepen = createSound("ppap.ahpineapplepen");
		ppap_ppap = createSound("ppap.ppap");
		keyboard_mechanical = createSound("keyboardmechanical");
		boi_summon = createSound("boi.spawn");
		boi_passive = createSound("boi.passive");
		boi_death = createSound("boi.death");
		shrek_summon = createSound("shrek.spawn");
		shrek_passive = createSound("shrek.passive");
		shrek_hit = createSound("shrek.hit");
		shrek_death = createSound("shrek.death");
		shrek_onion = createSound("shrek.onion");
		robbie_summon = createSound("robbie.summon");
		robbie_passive = createSound("robbie.passive");
		robbie_sax = createSound("robbie.sax");
		robbie_sax2 = createSound("robbie.sax2");
		robbie_hit = createSound("robbie.hit");
		robbie_death = createSound("robbie.death");
		dad_summon = createSound("dad.summon");
		dad_passive = createSound("dad.passive");
		dad_hit = createSound("dad.hit");
		dad_death = createSound("dad.death");
		leather_belt = createSound("leather.belt");
		cry = createSound("fa.cry");
		dankey_summon = createSound("dankey.summon");
		dankey_passive = createSound("dankey.passive");
		dankey_hit = createSound("dankey.hit");
		dankey_death = createSound("dankey.death");
		sanic_slow = createSound("sanic.slow");
		nigel_blagh = createSound("nigel.blagh");
		meme_music = createSound("meme.record1");
		meme_music2 = createSound("meme.record2");
		meme_music3 = createSound("meme.record3");
		meme_music4 = createSound("meme.record4");
		skywalker_sand = createSound("skywalker.sand");
		pills = createSound("pills.here");
		shaq_summon = createSound("shaq.summon");
		shaq_hit = createSound("shaq.hit");
		shaq_passive = createSound("shaq.passive");
		shaq_death = createSound("shaq.death");
		big_boi = createSound("meme.bigboi");
		hotdog_tune = createSound("hotdog.tune");
		hotdog_full = createSound("hotdog.full");
		heman_spawn = createSound("heman.summon");
		heman_hit = createSound("heman.hit");
		heman_passive = createSound("heman.passive");
		heman_death = createSound("heman.death");

		//start of main MEME registering
		ninethousand = createSound("9000");
		barrelroll = createSound("barrelroll");
		biwinning = createSound("bi.winning");
		boomheadshot = createSound("boomheadshot");
		callinthenext = createSound("callinthenext");
		cantbelieve = createSound("cantbelieve");
		charliebitme = createSound("charliebitme");
		chocolate = createSound("chocolate");
		congratz = createSound("congratz");
		dedidadedwam = createSound("dedidadedwam");
		deeznuts = createSound("deeznuts");
		doit = createSound("doit");
		dontletyourdreamsbedreams = createSound("dontletyourdreamsbedreams");
		doot = createSound("dootdoot");
		gaben = createSound("gaben");
		getitoxyclean = createSound("getitoxyclean");
		getnoscoped = createSound("getnoscoped");
		gotchab = createSound("gotchab");
		hagay = createSound("hahappy");
		k = createSound("k");
		leroyjenkins = createSound("leroyjenkins");
		momscar = createSound("momscar");
		morningscrub = createSound("morningscrub");
		nice = createSound("nice");
		nicememe = createSound("nicememe");
		noot = createSound("noot");
		nothisispatrick = createSound("nothisispatrick");
		nothisispatrick2 = createSound("nothisispatrick2");
		noticeme = createSound("noticeme");
		ohlongjohnson = createSound("ohlongjohnson");
		oldspicepower = createSound("oldspicepower");
		oxyclean = createSound("oxyclean");
		rightinthe = createSound("rightinthe");
		sandwich = createSound("sandwich");
		smokeweed = createSound("smokew");
		snooppengas = createSound("snooppen");
		somebodystopme = createSound("somebodystopme");
		sparta = createSound("sparta");
		spongebobsound = createSound("spongebobsound");
		triple = createSound("triple");
		trololo = createSound("trololo");
		victoryscreech = createSound("victoryscreech");
		wasted = createSound("wasted");
		whiten = createSound("whiten");
		wololo = createSound("wololo");
		wombocombo = createSound("wombocombo");
		wow = createSound("wow");
		wrong = createSound("wrong");
		wrongnumber = createSound("wrongnumber");
		thuglife = createSound("thug.life");
		boing = createSound("clippy.jump");
		clippy_mineshaft = createSound("clippy.mineshaft");
		clippy_cave = createSound("clippy.cave");
		clippy_night = createSound("clippy.night");
		clippy_health = createSound("clippy.health");
		clippy_death = createSound("clippy.death");
		clippy_hurt = createSound("clippy.hurt");
		clippy_passive = createSound("clippy.passive");
		clippy_forest = createSound("clippy.forest");
		knuckles_passive = createSound("knuckles.passive");
		knuckles_hurt = createSound("knuckles.hurt");
		knuckles_death = createSound("knuckles.death");
		rofl_spawn = createSound("rofl.summon");
		rofl_passive = createSound("rofl.passive");
		rofl_hurt = createSound("rofl.hurt");
		rofl_death = createSound("rofl.death");
		gnome_spawn = createSound("gnome.summon");
		gnome_passive = createSound("gnome.passive");
		gnome_hurt = createSound("gnome.hurt");
		gnome_death = createSound("gnome.death");
		phil_lottadamage = createSound("phil.lottadamage");
		phil_passive = createSound("phil.passive");
		phil_hurt = createSound("phil.hurt");
		phil_death = createSound("phil.death");
		sans_sound = createSound("sans.sound");
		tom_sound = createSound("tom.sound");
	}

	private static SoundEvent createSound(String name) {
		ResourceLocation resourceLocation = new ResourceLocation(Reference.MOD_ID, name);
		SoundEvent sound = new SoundEvent(resourceLocation);
		sound.setRegistryName(resourceLocation);
		sounds.add(sound);
		return sound;
	}

	@SubscribeEvent
	public static void registerSound(RegistryEvent.Register<SoundEvent> event) {
		for (SoundEvent sound : sounds) {
			event.getRegistry().register(sound);
		}
	}
}
